# Generated by Django 3.0.3 on 2020-02-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=5000)),
                ('headline', models.CharField(max_length=5000)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'ParseData',
            },
        ),
    ]
