# Generated by Django 3.0.3 on 2020-02-06 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('querypage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsedata',
            name='headline',
        ),
    ]
