# Generated by Django 3.0.3 on 2020-02-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querypage', '0002_remove_parsedata_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsedata',
            name='date',
            field=models.DateField(),
        ),
    ]
